# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'ComitandoSamples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GrowMartApp
  pod 'SwiftGen', '~> 6.0'

  target 'ComitandoSamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
